export const Transactions = [
  {
    name: 'John Dembe',
    currency: 'UGX',
    amount: 5846,
    transactionType: 'send',
    status: 'completed',
    time: '4 hr',
    icon: 'north_east',
    formattedTransactionType: 'Send Money',
  },
  {
    name: 'Mary Kaikara',
    currency: 'UGX',
    amount: 5846,
    transactionType: 'collect',
    status: 'completed',
    time: '4 hr',
    icon: 'south_east',
    formattedTransactionType: 'Collection',
  },
  {
    name: 'Philip Kenyanga',
    currency: 'UGX',
    amount: 5846,
    transactionType: 'collect',
    status: 'completed',
    time: '2 d',
    icon: 'south_east',
    formattedTransactionType: 'Collection',
  },
  {
    name: 'Nelson Kiza',
    currency: 'KES',
    amount: 8956,
    transactionType: 'send',
    status: 'pending',
    time: '4 hr',
    icon: 'north_east',
    formattedTransactionType: 'Send Money',
  },
  {
    name: 'Alice Mukassa',
    currency: 'UGX',
    amount: 5846,
    transactionType: 'send',
    status: 'failed',
    time: '5 d',
    icon: 'north_east',
    formattedTransactionType: 'Send Money',
  },
  {
    name: 'Mary Kaikara',
    currency: 'UGX',
    amount: 5846,
    transactionType: 'collect',
    status: 'completed',
    time: '4 hr',
    icon: 'south_east',
    formattedTransactionType: 'Send Money',
  },
  {
    name: 'Philip Kenyanga',
    currency: 'UGX',
    amount: 5846,
    transactionType: 'collect',
    status: 'completed',
    time: '2 d',
    icon: 'south_east',
    formattedTransactionType: 'Collection',
  },
  {
    name: 'Jerry Odhiambo',
    currency: 'KES',
    amount: 5846,
    transactionType: 'withdraw',
    status: 'completed',
    time: '8 d',
    icon: 'file_download',
    formattedTransactionType: 'Withdrawal',
  },
  {
    name: 'Nelson Kiza',
    currency: 'KES',
    amount: 8956,
    transactionType: 'send',
    status: 'pending',
    time: '4 hr',
    icon: 'north_east',
    formattedTransactionType: 'Send Money',
  },
  {
    name: 'Alice Mukassa',
    currency: 'UGX',
    amount: 5846,
    transactionType: 'send',
    status: 'failed',
    time: '5 d',
    icon: 'south_east',
    formattedTransactionType: 'Send Money',
  },
  {
    name: 'Mary Kaikara',
    currency: 'UGX',
    amount: 5846,
    transactionType: 'collect',
    status: 'completed',
    time: '4 hr',
    icon: 'south_east',
    formattedTransactionType: 'Send Money',
  },
];
